### ISSUE TITLE
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

### ISSUE THREAD

**Issue by fdanangp** [raniaamina/inkporter#14]
Inkporter show this error on **Inkscape 1.0.1** only.
KDE neon 
python3 version 3.8

> /usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
>   import fnmatch, glob, traceback, errno, sys, atexit, locale, imp
> Traceback (most recent call last):
>   File "inkporter.py", line 427, in <module>
>     e.run ()
>   File "/usr/share/inkscape/extensions/inkex/base.py", line 140, in run
>     self.save_raw(self.effect())
>   File "inkporter.py", line 393, in effect
>     self.svg.selected = {}
>   File "/usr/share/inkscape/extensions/inkex/elements/_base.py", line 169, in __setattr__
>     super(BaseElement, self).__setattr__(name, value)
> AttributeError: can't set attribute
> 

![Screenshot_20200914_144630](https://user-images.githubusercontent.com/10324059/93058659-dc058580-f699-11ea-8a95-b5dd793ff9af.png)

**Comment by raniaamina** [comment]
On review, it may be caused by update inx API due new release, we'll back soon.

**Comment by raniaamina** [comment]
Fixed!
Get latest update here:
https://inkscape.org/~raniaamina/%E2%98%85inkporter
