### ISSUE TITLE
I'm not able to export

### ISSUE THREAD

**Issue by rafadesign** [raniaamina/inkporter#15]
hello, i'm trying to export in inkscape using inkporter and it's not exporting

![Screenshot_20210102_212659](https://user-images.githubusercontent.com/46974593/103469264-681ee400-4d41-11eb-83d4-ad7f1295392b.png)

this message appears and the file does not appear in the destination folder, do you need any specific configuration?

**Comment by raniaamina** [comment]
Did you already set the object ID?

**Comment by rafadesign** [comment]
> Did you already set the object ID?

set of a group

**Comment by raniaamina** [comment]
Then set object ID of the group.
Ctrl Shift O, then fill the object ID field, i.e "My card".
Open inkporter then fill the field of Object ID pattern with "My Card" also.

**Comment by rafadesign** [comment]
> Then set object ID of the group.
> Ctrl Shift O, then fill the object ID field, i.e "My card".
> Open inkporter then fill the field of Object ID pattern with "My Card" also.

are several objects that have

**Comment by rafadesign** [comment]
> Then set object ID of the group.
> Ctrl Shift O, then fill the object ID field, i.e "My card".
> Open inkporter then fill the field of Object ID pattern with "My Card" also.

I did it, thank you very much

**Comment by raniaamina** [comment]
Great, i'll close this issue then👍
