### ISSUE TITLE
pdf: exported filters low resolution

### ISSUE THREAD

**Issue by KirstenRK** [raniaamina/inkporter#18]
Hi developers. 
First: I really really really love this extension. So thanks for making it. I am **really** loving it.

I was testing it on Windows 8.1, Inkscape 1.0.2-2.
It works very well. 
The only thing I found out, was when I export to pdf, with filtereffects, the resolution of the filters became too low.
And there was no setting for that.

It would help if I could set the dpi for rasterizing the filtereffects, when saving as pdf.
Just like when you save a pdf file in Inkscape, there is this question how much dpi you want for rasterizing the filter effect.

Thanks and good luck!

**Comment by raniaamina** [comment]
Hi @KirstenRK, thanks for feedback
so sorry about late reply this issue.

We can't promise to bring the update of Inkporter soon but we'll. Currently we'll focus on Citramanik (the next generation of Inkporter) development, and maybe we'll use your information to improve it.

**Comment by KirstenRK** [comment]
Hi Raniaamina,
In Citramanik the filter were exported with the right resolution.
There it works great.
Good luck with the developments!

Kirsten.

**Comment by raniaamina** [comment]
I checked the extension code, the problem of DPI in PDF rasterized filter only appear in windows, it works well ini linux, so we'll fix this.

**Comment by maslanangdev** [comment]
the issue already fixed, now you can specify dpi value for rasterized effects on pdf and eps

**Comment by raniaamina** [comment]
@KirstenRK would you check it please?

https://github.com/raniaamina/inkporter/tree/inkporter-gui

**Comment by KirstenRK** [comment]
@raniaamina It works here on my Windows 8.1 with Inkscape 1.0.2-2.

The filters are exported with the correct dpi! This is a huge step forward, instead of making a bitmap copy and then using Scribus for exporting with CMYK.

Thank you so much. I will do my best to promote your work, it is a very important plugin.

**Comment by raniaamina** [comment]
@KirstenRK, glad to hear that, also thanks for your work!
Since it solved, we can close this ticket :")

**Comment by KirstenRK** [comment]
@raniaamina Yes, I am new to github. I will close the ticket, wasn't sure that is up to me or you the developers.. 
With a smile here too!
