### ISSUE TITLE
W10 Inkscape 1.1 issue

### ISSUE THREAD

**Issue by oosterhagen** [raniaamina/inkporter#20]
Dear Rani,
while trying to export I ge this error message":

Traceback (most recent call last):
  File "inkporter.py", line 479, in <module>
    e.run ()
  File "C:\Program Files\inkscape\share\inkscape\extensions\inkex\base.py", line 131, in run
    self.save_raw(self.effect())
  File "inkporter.py", line 443, in effect
    new_nss = inkex.utils.NSS
AttributeError: module 'inkex.utils' has no attribute 'NSS'

I tried to find inkporter.py but can't find it anywhere. I hoped to solve it myself. Now I have to bother you with it. Excuses.

inkporter was installed by the extension manager 0.9.7

**Comment by oosterhagen** [comment]
Installed the extension from the release page (https://github.com/raniaamina/inkporter/releases) and now it works flawless.

Etension manager screws things up.

**Comment by raniaamina** [comment]
Great, so sorry for late reply your ticket
