### ISSUE TITLE
error when exporting

### ISSUE THREAD

**Issue by rafadesign** [raniaamina/inkporter#21]
I'm using inkscape 1.1 and I'm having trouble exporting
![image](https://user-images.githubusercontent.com/46974593/122586513-28b82b80-d033-11eb-8ed8-6a7528429e02.png)

OS: Fedora 34

**Comment by raniaamina** [comment]
You can try latest release of Inkporter.
https://inkscape.org/~raniaamina/%E2%98%85inkporter

we fixed it in this release
