### ISSUE TITLE
What's the license for this program?

### ISSUE THREAD

**Issue by felipesanches** [raniaamina/inkporter#22]
I was not able to find the licensing terms for this project. If it still does not have a license specified, I would like to suggest you choose one. Even though there are many options, in general, you are more likely to choose one of these:

* "GPL v3 or later"
* "MIT license"

But be sure to read about them before choosing.

**Comment by felipesanches** [comment]
I see that on https://github.com/artemtech/inkscape-gradient-saver you used "GPLv3+", so that is likely a good choice for you.

**Comment by raniaamina** [comment]
It should GPL v3, i'll add it soon
Big Thanks :")

**Comment by felipesanches** [comment]
thanks!

**Comment by raniaamina** [comment]
Done with: Commit [ee77fd](https://github.com/raniaamina/inkporter/commit/ee77fd87cb9dc4ad1e8952e8ab9a55e66fa3abf4)
